apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
  process: 
        matchPaths: 
        - path: /bin/cat
          onDirectory: 
          - path: ~/.ssh/
          - path: ~/.gnupg/
          - path: /usr/local/share/ca-certificate/
        matchPaths: 
        - path: /bin/cp
          onDirectory: 
          - path: ~/.ssh/
          - path: ~/.gnupg/
          - path: /usr/local/share/ca-certificate/          
  action:
    Block
  severity: 5