apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access
spec:
  selector:
      matchLabels:
          container: ubuntu-1
  process: 
        matchPaths: 
        - path: /bin/cat
          onFiles: 
          - path: /etc/passwd
          - path: /etc/shadow
         matchPaths: 
        - path: /bin/cp
          onFiles: 
          - path: /etc/passwd
          - path: /etc/shadow              
  action:
    Audit
  severity: 3