apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
  process: 
        matchPaths: 
        - path: /bin/cat
          onDirectory: 
          - path: /usr/local/share/ca-certificate/
            recurisve: true
        matchPaths: 
        - path: /bin/cp
          onDirectory: 
          - path: /usr/local/share/ca-certificate/
            recurisve: true        
  action:
    Audit
  severity: 5